---
title: "TP1"
output: html_document
date: "2024-02-01"
---

# TP1

```{r}

install.packages("dplyr")
install.packages("sf")

library(dplyr)
library(sf)
```

### Question 1 

```{r}

fond_communal <- st_read("Fonds_de_carte/commune_francemetro_2021.shp", options = "ENCODING=WINDOWS-1252")

```
### Question 2 

```{r}

summarise(fond_communal)

```

### Question 3 

```{r}

head(fond_communal, n=10)

```
### Question 4 

```{r}

projection <- st_crs(fond_communal)

print(projection)

```

### Question 5 

```{r}

communes_Bretagne <- fond_communal %>%
  filter(dep %in% c("22", "29", "56", "35"))%>%
  select(code, libelle, epc, dep, surf)

print(communes_Bretagne)

```
La variable géometry est également conservée.

### Question 6

```{r}

class(communes_Bretagne)

```

### Question 7

```{r}

plot(communes_Bretagne, lwd = 2)

```

### Question 8

```{r}

plot(st_geometry(communes_Bretagne))

```
### Question 9 

```{r}

communes_Bretagne$surf2 <- st_area(communes_Bretagne$geometry)
str(communes_Bretagne$surf2)

```

L'unité de mesure est le m^2.

### Question 10 

```{r}

communes_Bretagne$surf2 <- units::set_units(communes_Bretagne$surf2, "km^2")

```

### Question 11 

```{r}

str(communes_Bretagne$surf)
str(communes_Bretagne$surf2)

```

cE NE SONT PAS LES MÊMES VALEURS DANS SURF ET SURF2; CELA EST NORMAL PUISQUE NOUS N'AVONS PAS LA MÊME UNITE DE MESURE.

```{r}

dept_bretagne <- communes_Bretagne %>%
  group_by(dep) %>%
  summarise(surf_dept = sum(surf))

plot(st_geometry(dept_bretagne))

```

### Question 13

```{r}

fond_dept_bretagne <- communes_Bretagne %>%
  group_by(dep) %>%
  summarise(geometry = st_union(geometry))

plot(st_geometry(fond_dept_bretagne))

```

### Question 14 (+14-c)

```{r}

centroid_dept_bretagne <- fond_dept %>%
  st_centroid() %>% 
  mutate(dept_lib = c("cote d'Armor", "finistere", "ile et villaine", "morbihan"))

```

### Question 14-a 

```{r}

print(st_geometry_type(centroid_dept_bretagne))

```

### Question 14-b 
```{r}

plot(st_geometry(dept_bretagne))
plot(st_geometry(centroid_dept_bretagne), add=TRUE)

```

### Question 14-d

```{r}

coordonees_centroid <- st_coordinates(centroid_dept_bretagne)
plot(st_geometry(dept_bretagne))
plot(st_geometry(centroid_dept_bretagne), add=TRUE)
text(coordonees_centroid$x, coordonees_centroid$y, label = centroid_dept_bretagne$dept_lib)

```






